[2025-02-18T10:44:26.776+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T10:44:26.788+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T10:44:26.167489+00:00 [queued]>
[2025-02-18T10:44:26.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T10:44:26.167489+00:00 [queued]>
[2025-02-18T10:44:26.795+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T10:44:26.819+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): batch_processor> on 2025-02-18 10:44:26.167489+00:00
[2025-02-18T10:44:26.826+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'batch_processor', 'manual__2025-02-18T10:44:26.167489+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmpa8m_impn']
[2025-02-18T10:44:26.828+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask batch_processor
[2025-02-18T10:44:26.829+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T10:44:26.830+0000] {standard_task_runner.py:72} INFO - Started process 486 to run task
[2025-02-18T10:44:26.866+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T10:44:26.167489+00:00 [running]> on host e617448c6e59
[2025-02-18T10:44:26.938+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='batch_processor' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T10:44:26.167489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T10:44:26.167489+00:00'
[2025-02-18T10:44:26.939+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T10:44:26.975+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T10:44:26.976+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /usr/local/app/services/spark_streaming_processor.py']
[2025-02-18T10:44:26.982+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T10:44:29.119+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-18T10:44:29.119+0000] {subprocess.py:106} INFO -   File "/usr/local/app/services/spark_streaming_processor.py", line 5, in <module>
[2025-02-18T10:44:29.121+0000] {subprocess.py:106} INFO -     from services.snowflake_query_service import SnowflakeQueryService
[2025-02-18T10:44:29.121+0000] {subprocess.py:106} INFO -   File "/usr/local/app/services/snowflake_query_service.py", line 3, in <module>
[2025-02-18T10:44:29.123+0000] {subprocess.py:106} INFO -     from Config import snow_flake_conf  # âœ… Import credentials from config.py
[2025-02-18T10:44:29.124+0000] {subprocess.py:106} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-18T10:44:29.124+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'Config'
[2025-02-18T10:44:29.233+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-18T10:44:29.241+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-18T10:44:29.245+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kafka_streaming_process_pipeline, task_id=batch_processor, run_id=manual__2025-02-18T10:44:26.167489+00:00, execution_date=20250218T104426, start_date=20250218T104426, end_date=20250218T104429
[2025-02-18T10:44:29.256+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T10:44:29.256+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task batch_processor (Bash command failed. The command returned a non-zero exit code 1.; 486)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-18T10:44:29.292+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T10:44:29.305+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T10:44:29.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
