[2025-02-18T14:22:57.795+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T14:22:57.810+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T14:22:57.284812+00:00 [queued]>
[2025-02-18T14:22:57.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T14:22:57.284812+00:00 [queued]>
[2025-02-18T14:22:57.817+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T14:22:57.831+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): batch_processor> on 2025-02-18 14:22:57.284812+00:00
[2025-02-18T14:22:57.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'batch_processor', 'manual__2025-02-18T14:22:57.284812+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmp4hplq8qz']
[2025-02-18T14:22:57.839+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask batch_processor
[2025-02-18T14:22:57.839+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T14:22:57.840+0000] {standard_task_runner.py:72} INFO - Started process 411 to run task
[2025-02-18T14:22:57.875+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.batch_processor manual__2025-02-18T14:22:57.284812+00:00 [running]> on host 944871224fc0
[2025-02-18T14:22:57.945+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='batch_processor' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T14:22:57.284812+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T14:22:57.284812+00:00'
[2025-02-18T14:22:57.946+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T14:22:57.960+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T14:22:57.961+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /usr/local/app/services/spark_batch_processor.py']
[2025-02-18T14:22:57.969+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T14:22:59.611+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-18T14:23:00.230+0000] {subprocess.py:106} INFO - %6|1739888580.230|GETSUBSCRIPTIONS|ccloud-python-client-00816959-7fc0-4d75-98d8-88c7998cc97d#producer-1| [thrd:main]: Telemetry client instance id changed from AAAAAAAAAAAAAAAAAAAAAA to txKDB0qqRfSwjmRFCkktAg
[2025-02-18T14:23:01.003+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-02-18T14:23:01.003+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-02-18T14:23:01.214+0000] {subprocess.py:106} INFO - 25/02/18 14:23:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-18T14:23:02.158+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:02,158 - INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-02-18T14:23:02.159+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:02,158 - INFO - Connecting to GLOBAL Snowflake domain
[2025-02-18T14:23:02.159+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:02,158 - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-18T14:23:02.159+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:02,159 - INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2025-02-18T14:23:02.693+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:02,693 - INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2025-02-18T14:23:03.118+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:03,118 - INFO - âœ… Connected to Snowflake
[2025-02-18T14:23:03.119+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:03,118 - INFO - Reading Movies.txt file...
[2025-02-18T14:23:03.951+0000] {subprocess.py:106} INFO - 2025-02-18 14:23:03,951 - ERROR - Error in batch processing: [PATH_NOT_FOUND] Path does not exist: file:/app/data/raw/Movies.txt.
[2025-02-18T14:23:38.203+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-18T14:23:38.204+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T14:23:38.205+0000] {process_utils.py:132} INFO - Sending 15 to group 411. PIDs of all processes in the group: [413, 434, 411]
[2025-02-18T14:23:38.206+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 411
[2025-02-18T14:23:38.206+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-18T14:23:38.207+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-02-18T14:23:38.225+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T14:23:38.233+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=413, status='terminated', started='14:22:56') (413) terminated with exit code None
[2025-02-18T14:23:38.607+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=434, status='terminated', started='14:22:58') (434) terminated with exit code None
[2025-02-18T14:23:38.608+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=411, status='terminated', exitcode=0, started='14:22:56') (411) terminated with exit code 0
