[2025-02-17T14:41:28.699+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T14:41:28.711+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.start_kafka_producers manual__2025-02-17T14:41:12.783914+00:00 [queued]>
[2025-02-17T14:41:28.719+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.start_kafka_producers manual__2025-02-17T14:41:12.783914+00:00 [queued]>
[2025-02-17T14:41:28.720+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-17T14:41:28.731+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): start_kafka_producers> on 2025-02-17 14:41:12.783914+00:00
[2025-02-17T14:41:28.736+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'start_kafka_producers', 'manual__2025-02-17T14:41:12.783914+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmpnsy7fb90']
[2025-02-17T14:41:28.739+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask start_kafka_producers
[2025-02-17T14:41:28.739+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1073) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-17T14:41:28.740+0000] {standard_task_runner.py:72} INFO - Started process 1074 to run task
[2025-02-17T14:41:28.770+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.start_kafka_producers manual__2025-02-17T14:41:12.783914+00:00 [running]> on host 3823dca5ba70
[2025-02-17T14:41:28.832+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='start_kafka_producers' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T14:41:12.783914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T14:41:12.783914+00:00'
[2025-02-17T14:41:28.833+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-17T14:41:28.846+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-17T14:41:28.847+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /usr/local/app/kafka/UserActivitySimulator.py']
[2025-02-17T14:41:28.854+0000] {subprocess.py:99} INFO - Output:
[2025-02-17T14:41:29.927+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-17T14:41:31.192+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-02-17T14:41:31.193+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-02-17T14:41:31.317+0000] {subprocess.py:106} INFO - 25/02/17 14:41:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-17T14:41:32.262+0000] {subprocess.py:106} INFO - ERROR:root:Error initializing Kafka Producer: KafkaError{code=_INVALID_ARG,val=-186,str="Configuration property "security.protocol" cannot be set to empty value"}
[2025-02-17T14:41:32.263+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-17T14:41:32.263+0000] {subprocess.py:106} INFO -   File "/usr/local/app/kafka/UserActivitySimulator.py", line 93, in <module>
[2025-02-17T14:41:32.265+0000] {subprocess.py:106} INFO -     producer = KafkaProducer(producer_conf, schema_registry_url, auth_user_info)
[2025-02-17T14:41:32.265+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-17T14:41:32.265+0000] {subprocess.py:106} INFO -   File "/usr/local/app/kafka/KafkaProducer.py", line 18, in __init__
[2025-02-17T14:41:32.266+0000] {subprocess.py:106} INFO -     self._initialize_producer()
[2025-02-17T14:41:32.267+0000] {subprocess.py:106} INFO -   File "/usr/local/app/kafka/KafkaProducer.py", line 24, in _initialize_producer
[2025-02-17T14:41:32.268+0000] {subprocess.py:106} INFO -     self.producer = Producer(self.config)
[2025-02-17T14:41:32.268+0000] {subprocess.py:106} INFO -                     ^^^^^^^^^^^^^^^^^^^^^
[2025-02-17T14:41:32.269+0000] {subprocess.py:106} INFO - cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Configuration property "security.protocol" cannot be set to empty value"}
[2025-02-17T14:41:32.726+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-17T14:41:32.735+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-17T14:41:32.739+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kafka_streaming_process_pipeline, task_id=start_kafka_producers, run_id=manual__2025-02-17T14:41:12.783914+00:00, execution_date=20250217T144112, start_date=20250217T144128, end_date=20250217T144132
[2025-02-17T14:41:32.750+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-17T14:41:32.751+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task start_kafka_producers (Bash command failed. The command returned a non-zero exit code 1.; 1074)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-17T14:41:32.766+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T14:41:32.778+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T14:41:32.780+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
